---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: hpa
  namespace: {{ TNF_EXAMPLE_CNF_NAMESPACE }}
spec:
  replicas: 2
  selector:
    matchLabels:
      app: hpa
  template:
    metadata:
      labels:
        app: hpa
        test-network-function.com/generic: target
        test-network-function.com/container: target
      annotations:
        test-network-function.com/defaultnetworkinterface: '"eth0"' # optional
      name: hpa
    spec:
      containers:
        - command: [ "/bin/bash", "-c", "echo 'logs' && tail -f /dev/null" ]
          image: quay.io/testnetworkfunction/cnf-test-partner:latest
          name: hpa
          resources:
            limits:
              memory: 512Mi
              cpu: 0.25
          lifecycle:
            preStop:
              exec:
                command: ["/bin/sh", "-c", "killall -0 tail"]
      affinity:
        podAntiAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            - labelSelector:
                matchExpressions:
                  - key: app
                    operator: In
                    values:
                      - hpa
              topologyKey: "kubernetes.io/hostname"
